const examensActionTypes = {
  ADD_EXAMEN: 'ADD_EXAMEN',
  ADD_TO_SELECTED_EXAMENS: 'ADD_TO_SELECTED_EXAMENS',
  RESET: 'RESET',
  SET_IS_AMO: 'SET_IS_AMO',
  DELETE_EXAMEN_FROM_SELECTED_EXAMENS: 'DELETE_EXAMEN_FROM_SELECTED_EXAMENS',
};
export default examensActionTypes;
